name: docker build filebot-beta

on:
  workflow_run:
    workflows:
      - 'docker build filebot-xpra'
    types:
      - 'completed'
  push:
    paths:
      - '.github/workflows/docker.beta.yml'
      - 'Dockerfile.beta'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.beta
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/filebot:beta
          cache-from: type=gha
          cache-to: type=gha,mode=max
