name: docker build filebot-beta

on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'Revision'
        type: 'choice'
        default: 'latest'
        options:
        - 'latest'
  schedule:
      - cron: '0 0 8 * *'
  workflow_run:
    workflows:
      - 'docker build filebot-xpra'
    types:
      - 'completed'
  push:
    paths:
      - '.github/workflows/docker.beta.yml'
      - 'Dockerfile.beta'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-beta-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-beta-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.beta
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/filebot:beta
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
